apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: todo-app
  namespaceSelector:
    matchNames:
      - testprod
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
