apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-config
  namespace: testprod
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_NAME: {{ .Values.env.APP_NAME | quote }}

